import type { RegionMapping, DistrictMapping } from "./types";

export const REGIONS: RegionMapping[] = [
  { name: "서울특별시", slug: "seoul", apiCode: "6110000_ALL" },
  { name: "부산광역시", slug: "busan", apiCode: "6260000_ALL" },
  { name: "대구광역시", slug: "daegu", apiCode: "6270000_ALL" },
  { name: "인천광역시", slug: "incheon", apiCode: "6280000_ALL" },
  { name: "광주광역시", slug: "gwangju", apiCode: "6290000_ALL" },
  { name: "대전광역시", slug: "daejeon", apiCode: "6300000_ALL" },
  { name: "울산광역시", slug: "ulsan", apiCode: "6310000_ALL" },
  { name: "세종특별자치시", slug: "sejong", apiCode: "5690000_ALL" },
  { name: "경기도", slug: "gyeonggi", apiCode: "6410000_ALL" },
  { name: "강원특별자치도", slug: "gangwon", apiCode: "6530000_ALL" },
  { name: "충청북도", slug: "chungbuk", apiCode: "6430000_ALL" },
  { name: "충청남도", slug: "chungnam", apiCode: "6440000_ALL" },
  { name: "전북특별자치도", slug: "jeonbuk", apiCode: "6540000_ALL" },
  { name: "전라남도", slug: "jeonnam", apiCode: "6460000_ALL" },
  { name: "경상북도", slug: "gyeongbuk", apiCode: "6470000_ALL" },
  { name: "경상남도", slug: "gyeongnam", apiCode: "6480000_ALL" },
  { name: "제주특별자치도", slug: "jeju", apiCode: "6500000_ALL" },
];

export const DISTRICTS: DistrictMapping[] = [
  // ===== 서울특별시 (25개구) =====
  { name: "강남구", slug: "gangnam", regionSlug: "seoul", apiCode: "3220000" },
  { name: "강동구", slug: "gangdong", regionSlug: "seoul", apiCode: "3240000" },
  { name: "강북구", slug: "gangbuk", regionSlug: "seoul", apiCode: "3080000" },
  { name: "강서구", slug: "gangseo", regionSlug: "seoul", apiCode: "3150000" },
  { name: "관악구", slug: "gwanak", regionSlug: "seoul", apiCode: "3200000" },
  { name: "광진구", slug: "gwangjin", regionSlug: "seoul", apiCode: "3040000" },
  { name: "구로구", slug: "guro", regionSlug: "seoul", apiCode: "3160000" },
  { name: "금천구", slug: "geumcheon", regionSlug: "seoul", apiCode: "3170000" },
  { name: "노원구", slug: "nowon", regionSlug: "seoul", apiCode: "3100000" },
  { name: "도봉구", slug: "dobong", regionSlug: "seoul", apiCode: "3090000" },
  { name: "동대문구", slug: "dongdaemun", regionSlug: "seoul", apiCode: "3050000" },
  { name: "동작구", slug: "dongjak", regionSlug: "seoul", apiCode: "3190000" },
  { name: "마포구", slug: "mapo", regionSlug: "seoul", apiCode: "3130000" },
  { name: "서대문구", slug: "seodaemun", regionSlug: "seoul", apiCode: "3120000" },
  { name: "서초구", slug: "seocho", regionSlug: "seoul", apiCode: "3210000" },
  { name: "성동구", slug: "seongdong", regionSlug: "seoul", apiCode: "3030000" },
  { name: "성북구", slug: "seongbuk", regionSlug: "seoul", apiCode: "3070000" },
  { name: "송파구", slug: "songpa", regionSlug: "seoul", apiCode: "3230000" },
  { name: "양천구", slug: "yangcheon", regionSlug: "seoul", apiCode: "3140000" },
  { name: "영등포구", slug: "yeongdeungpo", regionSlug: "seoul", apiCode: "3180000" },
  { name: "용산구", slug: "yongsan", regionSlug: "seoul", apiCode: "3020000" },
  { name: "은평구", slug: "eunpyeong", regionSlug: "seoul", apiCode: "3110000" },
  { name: "종로구", slug: "jongno", regionSlug: "seoul", apiCode: "3000000" },
  { name: "중구", slug: "junggu", regionSlug: "seoul", apiCode: "3010000" },
  { name: "중랑구", slug: "jungnang", regionSlug: "seoul", apiCode: "3060000" },

  // ===== 부산광역시 (16개 구/군) =====
  { name: "강서구", slug: "bsgangseo", regionSlug: "busan", apiCode: "3360000" },
  { name: "금정구", slug: "geumjeong", regionSlug: "busan", apiCode: "3350000" },
  { name: "기장군", slug: "gijang", regionSlug: "busan", apiCode: "3400000" },
  { name: "남구", slug: "bsnamgu", regionSlug: "busan", apiCode: "3310000" },
  { name: "동구", slug: "bsdonggu", regionSlug: "busan", apiCode: "3270000" },
  { name: "동래구", slug: "dongnae", regionSlug: "busan", apiCode: "3300000" },
  { name: "부산진구", slug: "busanjin", regionSlug: "busan", apiCode: "3290000" },
  { name: "북구", slug: "bsbukgu", regionSlug: "busan", apiCode: "3320000" },
  { name: "사상구", slug: "sasang", regionSlug: "busan", apiCode: "3390000" },
  { name: "사하구", slug: "saha", regionSlug: "busan", apiCode: "3340000" },
  { name: "서구", slug: "bsseogu", regionSlug: "busan", apiCode: "3260000" },
  { name: "수영구", slug: "suyeong", regionSlug: "busan", apiCode: "3380000" },
  { name: "연제구", slug: "yeonje", regionSlug: "busan", apiCode: "3370000" },
  { name: "영도구", slug: "yeongdo", regionSlug: "busan", apiCode: "3280000" },
  { name: "중구", slug: "bsjunggu", regionSlug: "busan", apiCode: "3250000" },
  { name: "해운대구", slug: "haeundae", regionSlug: "busan", apiCode: "3330000" },

  // ===== 대구광역시 (8개 구/군) =====
  { name: "남구", slug: "dgnamgu", regionSlug: "daegu", apiCode: "3440000" },
  { name: "달서구", slug: "dalseo", regionSlug: "daegu", apiCode: "3470000" },
  { name: "달성군", slug: "dalseong", regionSlug: "daegu", apiCode: "3480000" },
  { name: "동구", slug: "dgdonggu", regionSlug: "daegu", apiCode: "3420000" },
  { name: "북구", slug: "dgbukgu", regionSlug: "daegu", apiCode: "3450000" },
  { name: "서구", slug: "dgseogu", regionSlug: "daegu", apiCode: "3430000" },
  { name: "수성구", slug: "suseong", regionSlug: "daegu", apiCode: "3460000" },
  { name: "중구", slug: "dgjunggu", regionSlug: "daegu", apiCode: "3410000" },
  { name: "군위군", slug: "gunwi", regionSlug: "daegu", apiCode: "3490000" },

  // ===== 인천광역시 (10개 구/군) =====
  { name: "계양구", slug: "gyeyang", regionSlug: "incheon", apiCode: "3560000" },
  { name: "남동구", slug: "namdong", regionSlug: "incheon", apiCode: "3550000" },
  { name: "동구", slug: "icdonggu", regionSlug: "incheon", apiCode: "3510000" },
  { name: "미추홀구", slug: "michuhol", regionSlug: "incheon", apiCode: "3520000" },
  { name: "부평구", slug: "bupyeong", regionSlug: "incheon", apiCode: "3540000" },
  { name: "서구", slug: "icseogu", regionSlug: "incheon", apiCode: "3570000" },
  { name: "연수구", slug: "yeonsu", regionSlug: "incheon", apiCode: "3530000" },
  { name: "중구", slug: "icjunggu", regionSlug: "incheon", apiCode: "3500000" },
  { name: "강화군", slug: "ganghwa", regionSlug: "incheon", apiCode: "3580000" },
  { name: "옹진군", slug: "ongjin", regionSlug: "incheon", apiCode: "3590000" },

  // ===== 광주광역시 (5개구) =====
  { name: "광산구", slug: "gwangsan", regionSlug: "gwangju", apiCode: "3640000" },
  { name: "남구", slug: "gjnamgu", regionSlug: "gwangju", apiCode: "3620000" },
  { name: "동구", slug: "gjdonggu", regionSlug: "gwangju", apiCode: "3600000" },
  { name: "북구", slug: "gjbukgu", regionSlug: "gwangju", apiCode: "3630000" },
  { name: "서구", slug: "gjseogu", regionSlug: "gwangju", apiCode: "3610000" },

  // ===== 대전광역시 (5개구) =====
  { name: "대덕구", slug: "daedeok", regionSlug: "daejeon", apiCode: "3690000" },
  { name: "동구", slug: "djdonggu", regionSlug: "daejeon", apiCode: "3650000" },
  { name: "서구", slug: "djseogu", regionSlug: "daejeon", apiCode: "3670000" },
  { name: "유성구", slug: "yuseong", regionSlug: "daejeon", apiCode: "3680000" },
  { name: "중구", slug: "djjunggu", regionSlug: "daejeon", apiCode: "3660000" },

  // ===== 울산광역시 (5개 구/군) =====
  { name: "남구", slug: "usnamgu", regionSlug: "ulsan", apiCode: "3710000" },
  { name: "동구", slug: "usdonggu", regionSlug: "ulsan", apiCode: "3700000" },
  { name: "북구", slug: "usbukgu", regionSlug: "ulsan", apiCode: "3720000" },
  { name: "울주군", slug: "ulju", regionSlug: "ulsan", apiCode: "3730000" },
  { name: "중구", slug: "usjunggu", regionSlug: "ulsan", apiCode: "3740000" },

  // ===== 세종특별자치시 (1개) =====
  { name: "세종시", slug: "sejongsi", regionSlug: "sejong", apiCode: "5690000" },

  // ===== 경기도 (31개 시/군) =====
  { name: "가평군", slug: "gapyeong", regionSlug: "gyeonggi", apiCode: "3870000" },
  { name: "고양시", slug: "goyang", regionSlug: "gyeonggi", apiCode: "3790000" },
  { name: "과천시", slug: "gwacheon", regionSlug: "gyeonggi", apiCode: "3820000" },
  { name: "광명시", slug: "gwangmyeong", regionSlug: "gyeonggi", apiCode: "3780000" },
  { name: "광주시", slug: "ggwangju", regionSlug: "gyeonggi", apiCode: "3850000" },
  { name: "구리시", slug: "guri", regionSlug: "gyeonggi", apiCode: "3830000" },
  { name: "군포시", slug: "gunpo", regionSlug: "gyeonggi", apiCode: "3810000" },
  { name: "김포시", slug: "gimpo", regionSlug: "gyeonggi", apiCode: "3890000" },
  { name: "남양주시", slug: "namyangju", regionSlug: "gyeonggi", apiCode: "3830000" },
  { name: "동두천시", slug: "dongducheon", regionSlug: "gyeonggi", apiCode: "3770000" },
  { name: "부천시", slug: "bucheon", regionSlug: "gyeonggi", apiCode: "3780000" },
  { name: "성남시", slug: "seongnam", regionSlug: "gyeonggi", apiCode: "3760000" },
  { name: "수원시", slug: "suwon", regionSlug: "gyeonggi", apiCode: "3750000" },
  { name: "시흥시", slug: "siheung", regionSlug: "gyeonggi", apiCode: "3800000" },
  { name: "안산시", slug: "ansan", regionSlug: "gyeonggi", apiCode: "3800000" },
  { name: "안성시", slug: "anseong", regionSlug: "gyeonggi", apiCode: "3860000" },
  { name: "안양시", slug: "anyang", regionSlug: "gyeonggi", apiCode: "3760000" },
  { name: "양주시", slug: "yangju", regionSlug: "gyeonggi", apiCode: "3880000" },
  { name: "양평군", slug: "yangpyeong", regionSlug: "gyeonggi", apiCode: "3870000" },
  { name: "여주시", slug: "yeoju", regionSlug: "gyeonggi", apiCode: "3860000" },
  { name: "연천군", slug: "yeoncheon", regionSlug: "gyeonggi", apiCode: "3880000" },
  { name: "오산시", slug: "osan", regionSlug: "gyeonggi", apiCode: "3810000" },
  { name: "용인시", slug: "yongin", regionSlug: "gyeonggi", apiCode: "3840000" },
  { name: "의왕시", slug: "uiwang", regionSlug: "gyeonggi", apiCode: "3820000" },
  { name: "의정부시", slug: "uijeongbu", regionSlug: "gyeonggi", apiCode: "3770000" },
  { name: "이천시", slug: "icheon", regionSlug: "gyeonggi", apiCode: "3850000" },
  { name: "파주시", slug: "paju", regionSlug: "gyeonggi", apiCode: "3890000" },
  { name: "평택시", slug: "pyeongtaek", regionSlug: "gyeonggi", apiCode: "3760000" },
  { name: "포천시", slug: "pocheon", regionSlug: "gyeonggi", apiCode: "3880000" },
  { name: "하남시", slug: "hanam", regionSlug: "gyeonggi", apiCode: "3840000" },
  { name: "화성시", slug: "hwaseong", regionSlug: "gyeonggi", apiCode: "3810000" },

  // ===== 강원특별자치도 (18개 시/군) =====
  { name: "강릉시", slug: "gangneung", regionSlug: "gangwon", apiCode: "3930000" },
  { name: "고성군", slug: "gwgoseong", regionSlug: "gangwon", apiCode: "3960000" },
  { name: "동해시", slug: "donghae", regionSlug: "gangwon", apiCode: "3940000" },
  { name: "삼척시", slug: "samcheok", regionSlug: "gangwon", apiCode: "3950000" },
  { name: "속초시", slug: "sokcho", regionSlug: "gangwon", apiCode: "3950000" },
  { name: "양구군", slug: "yanggu", regionSlug: "gangwon", apiCode: "3960000" },
  { name: "양양군", slug: "yangyang", regionSlug: "gangwon", apiCode: "3970000" },
  { name: "영월군", slug: "yeongwol", regionSlug: "gangwon", apiCode: "3940000" },
  { name: "원주시", slug: "wonju", regionSlug: "gangwon", apiCode: "3920000" },
  { name: "인제군", slug: "inje", regionSlug: "gangwon", apiCode: "3960000" },
  { name: "정선군", slug: "jeongseon", regionSlug: "gangwon", apiCode: "3950000" },
  { name: "철원군", slug: "cheorwon", regionSlug: "gangwon", apiCode: "3960000" },
  { name: "춘천시", slug: "chuncheon", regionSlug: "gangwon", apiCode: "3910000" },
  { name: "태백시", slug: "taebaek", regionSlug: "gangwon", apiCode: "3940000" },
  { name: "평창군", slug: "pyeongchang", regionSlug: "gangwon", apiCode: "3950000" },
  { name: "홍천군", slug: "hongcheon", regionSlug: "gangwon", apiCode: "3930000" },
  { name: "화천군", slug: "hwacheon", regionSlug: "gangwon", apiCode: "3960000" },
  { name: "횡성군", slug: "hoengseong", regionSlug: "gangwon", apiCode: "3920000" },

  // ===== 충청북도 (11개 시/군) =====
  { name: "괴산군", slug: "goesan", regionSlug: "chungbuk", apiCode: "4020000" },
  { name: "단양군", slug: "danyang", regionSlug: "chungbuk", apiCode: "4030000" },
  { name: "보은군", slug: "boeun", regionSlug: "chungbuk", apiCode: "4010000" },
  { name: "영동군", slug: "yeongdong", regionSlug: "chungbuk", apiCode: "4010000" },
  { name: "옥천군", slug: "okcheon", regionSlug: "chungbuk", apiCode: "4010000" },
  { name: "음성군", slug: "eumseong", regionSlug: "chungbuk", apiCode: "4020000" },
  { name: "제천시", slug: "jecheon", regionSlug: "chungbuk", apiCode: "4000000" },
  { name: "증평군", slug: "jeungpyeong", regionSlug: "chungbuk", apiCode: "4020000" },
  { name: "진천군", slug: "jincheon", regionSlug: "chungbuk", apiCode: "4020000" },
  { name: "청주시", slug: "cheongju", regionSlug: "chungbuk", apiCode: "3990000" },
  { name: "충주시", slug: "chungju", regionSlug: "chungbuk", apiCode: "3990000" },

  // ===== 충청남도 (15개 시/군) =====
  { name: "계룡시", slug: "gyeryong", regionSlug: "chungnam", apiCode: "4100000" },
  { name: "공주시", slug: "gongju", regionSlug: "chungnam", apiCode: "4040000" },
  { name: "금산군", slug: "geumsan", regionSlug: "chungnam", apiCode: "4080000" },
  { name: "논산시", slug: "nonsan", regionSlug: "chungnam", apiCode: "4090000" },
  { name: "당진시", slug: "dangjin", regionSlug: "chungnam", apiCode: "4110000" },
  { name: "보령시", slug: "boryeong", regionSlug: "chungnam", apiCode: "4050000" },
  { name: "부여군", slug: "buyeo", regionSlug: "chungnam", apiCode: "4080000" },
  { name: "서산시", slug: "seosan", regionSlug: "chungnam", apiCode: "4060000" },
  { name: "서천군", slug: "seocheon", regionSlug: "chungnam", apiCode: "4090000" },
  { name: "아산시", slug: "asan", regionSlug: "chungnam", apiCode: "4050000" },
  { name: "예산군", slug: "yesan", regionSlug: "chungnam", apiCode: "4090000" },
  { name: "천안시", slug: "cheonan", regionSlug: "chungnam", apiCode: "4040000" },
  { name: "청양군", slug: "cheongyang", regionSlug: "chungnam", apiCode: "4080000" },
  { name: "태안군", slug: "taean", regionSlug: "chungnam", apiCode: "4070000" },
  { name: "홍성군", slug: "hongseong", regionSlug: "chungnam", apiCode: "4070000" },

  // ===== 전북특별자치도 (14개 시/군) =====
  { name: "고창군", slug: "gochang", regionSlug: "jeonbuk", apiCode: "4190000" },
  { name: "군산시", slug: "gunsan", regionSlug: "jeonbuk", apiCode: "4130000" },
  { name: "김제시", slug: "gimje", regionSlug: "jeonbuk", apiCode: "4170000" },
  { name: "남원시", slug: "namwon", regionSlug: "jeonbuk", apiCode: "4150000" },
  { name: "무주군", slug: "muju", regionSlug: "jeonbuk", apiCode: "4180000" },
  { name: "부안군", slug: "buan", regionSlug: "jeonbuk", apiCode: "4200000" },
  { name: "순창군", slug: "sunchang", regionSlug: "jeonbuk", apiCode: "4190000" },
  { name: "완주군", slug: "wanju", regionSlug: "jeonbuk", apiCode: "4170000" },
  { name: "익산시", slug: "iksan", regionSlug: "jeonbuk", apiCode: "4140000" },
  { name: "임실군", slug: "imsil", regionSlug: "jeonbuk", apiCode: "4190000" },
  { name: "장수군", slug: "jangsu", regionSlug: "jeonbuk", apiCode: "4180000" },
  { name: "전주시", slug: "jeonju", regionSlug: "jeonbuk", apiCode: "4120000" },
  { name: "정읍시", slug: "jeongeup", regionSlug: "jeonbuk", apiCode: "4160000" },
  { name: "진안군", slug: "jinan", regionSlug: "jeonbuk", apiCode: "4180000" },

  // ===== 전라남도 (22개 시/군) =====
  { name: "강진군", slug: "gangjin", regionSlug: "jeonnam", apiCode: "4290000" },
  { name: "고흥군", slug: "goheung", regionSlug: "jeonnam", apiCode: "4270000" },
  { name: "곡성군", slug: "gokseong", regionSlug: "jeonnam", apiCode: "4240000" },
  { name: "광양시", slug: "gwangyang", regionSlug: "jeonnam", apiCode: "4230000" },
  { name: "구례군", slug: "gurye", regionSlug: "jeonnam", apiCode: "4240000" },
  { name: "나주시", slug: "naju", regionSlug: "jeonnam", apiCode: "4220000" },
  { name: "담양군", slug: "damyang", regionSlug: "jeonnam", apiCode: "4240000" },
  { name: "목포시", slug: "mokpo", regionSlug: "jeonnam", apiCode: "4210000" },
  { name: "무안군", slug: "muan", regionSlug: "jeonnam", apiCode: "4310000" },
  { name: "보성군", slug: "boseong", regionSlug: "jeonnam", apiCode: "4270000" },
  { name: "순천시", slug: "suncheon", regionSlug: "jeonnam", apiCode: "4220000" },
  { name: "신안군", slug: "sinan", regionSlug: "jeonnam", apiCode: "4320000" },
  { name: "여수시", slug: "yeosu", regionSlug: "jeonnam", apiCode: "4220000" },
  { name: "영광군", slug: "yeonggwang", regionSlug: "jeonnam", apiCode: "4310000" },
  { name: "영암군", slug: "yeongam", regionSlug: "jeonnam", apiCode: "4300000" },
  { name: "완도군", slug: "wando", regionSlug: "jeonnam", apiCode: "4300000" },
  { name: "장성군", slug: "jangseong", regionSlug: "jeonnam", apiCode: "4310000" },
  { name: "장흥군", slug: "jangheung", regionSlug: "jeonnam", apiCode: "4280000" },
  { name: "진도군", slug: "jindo", regionSlug: "jeonnam", apiCode: "4320000" },
  { name: "함평군", slug: "hampyeong", regionSlug: "jeonnam", apiCode: "4310000" },
  { name: "해남군", slug: "haenam", regionSlug: "jeonnam", apiCode: "4290000" },
  { name: "화순군", slug: "hwasun", regionSlug: "jeonnam", apiCode: "4260000" },

  // ===== 경상북도 (23개 시/군) =====
  { name: "경산시", slug: "gyeongsan", regionSlug: "gyeongbuk", apiCode: "4410000" },
  { name: "경주시", slug: "gyeongju", regionSlug: "gyeongbuk", apiCode: "4340000" },
  { name: "고령군", slug: "goryeong", regionSlug: "gyeongbuk", apiCode: "4430000" },
  { name: "구미시", slug: "gumi", regionSlug: "gyeongbuk", apiCode: "4370000" },
  { name: "김천시", slug: "gimcheon", regionSlug: "gyeongbuk", apiCode: "4350000" },
  { name: "문경시", slug: "mungyeong", regionSlug: "gyeongbuk", apiCode: "4390000" },
  { name: "봉화군", slug: "bonghwa", regionSlug: "gyeongbuk", apiCode: "4460000" },
  { name: "상주시", slug: "sangju", regionSlug: "gyeongbuk", apiCode: "4380000" },
  { name: "성주군", slug: "seongju", regionSlug: "gyeongbuk", apiCode: "4430000" },
  { name: "안동시", slug: "andong", regionSlug: "gyeongbuk", apiCode: "4360000" },
  { name: "영덕군", slug: "yeongdeok", regionSlug: "gyeongbuk", apiCode: "4450000" },
  { name: "영양군", slug: "yeongyang", regionSlug: "gyeongbuk", apiCode: "4450000" },
  { name: "영주시", slug: "yeongju", regionSlug: "gyeongbuk", apiCode: "4390000" },
  { name: "영천시", slug: "yeongcheon", regionSlug: "gyeongbuk", apiCode: "4400000" },
  { name: "예천군", slug: "yecheon", regionSlug: "gyeongbuk", apiCode: "4460000" },
  { name: "울릉군", slug: "ulleung", regionSlug: "gyeongbuk", apiCode: "4470000" },
  { name: "울진군", slug: "uljin", regionSlug: "gyeongbuk", apiCode: "4460000" },
  { name: "의성군", slug: "uiseong", regionSlug: "gyeongbuk", apiCode: "4420000" },
  { name: "청도군", slug: "cheongdo", regionSlug: "gyeongbuk", apiCode: "4430000" },
  { name: "청송군", slug: "cheongsong", regionSlug: "gyeongbuk", apiCode: "4440000" },
  { name: "칠곡군", slug: "chilgok", regionSlug: "gyeongbuk", apiCode: "4430000" },
  { name: "포항시", slug: "pohang", regionSlug: "gyeongbuk", apiCode: "4330000" },
  { name: "고령군", slug: "goryeong", regionSlug: "gyeongbuk", apiCode: "4430000" },

  // ===== 경상남도 (18개 시/군) =====
  { name: "거제시", slug: "geoje", regionSlug: "gyeongnam", apiCode: "4560000" },
  { name: "거창군", slug: "geochang", regionSlug: "gyeongnam", apiCode: "4590000" },
  { name: "고성군", slug: "gsngoseong", regionSlug: "gyeongnam", apiCode: "4570000" },
  { name: "김해시", slug: "gimhae", regionSlug: "gyeongnam", apiCode: "4530000" },
  { name: "남해군", slug: "namhae", regionSlug: "gyeongnam", apiCode: "4570000" },
  { name: "밀양시", slug: "miryang", regionSlug: "gyeongnam", apiCode: "4540000" },
  { name: "사천시", slug: "sacheon", regionSlug: "gyeongnam", apiCode: "4510000" },
  { name: "산청군", slug: "sancheong", regionSlug: "gyeongnam", apiCode: "4580000" },
  { name: "양산시", slug: "yangsan", regionSlug: "gyeongnam", apiCode: "4550000" },
  { name: "의령군", slug: "uiryeong", regionSlug: "gyeongnam", apiCode: "4560000" },
  { name: "진주시", slug: "jinju", regionSlug: "gyeongnam", apiCode: "4500000" },
  { name: "창녕군", slug: "changnyeong", regionSlug: "gyeongnam", apiCode: "4560000" },
  { name: "창원시", slug: "changwon", regionSlug: "gyeongnam", apiCode: "4490000" },
  { name: "통영시", slug: "tongyeong", regionSlug: "gyeongnam", apiCode: "4510000" },
  { name: "하동군", slug: "hadong", regionSlug: "gyeongnam", apiCode: "4580000" },
  { name: "함안군", slug: "haman", regionSlug: "gyeongnam", apiCode: "4560000" },
  { name: "함양군", slug: "hamyang", regionSlug: "gyeongnam", apiCode: "4580000" },
  { name: "합천군", slug: "hapcheon", regionSlug: "gyeongnam", apiCode: "4590000" },

  // ===== 제주특별자치도 (2개 시) =====
  { name: "제주시", slug: "jejusi", regionSlug: "jeju", apiCode: "4610000" },
  { name: "서귀포시", slug: "seogwipo", regionSlug: "jeju", apiCode: "4620000" },
];

// Helper functions
export function getRegionBySlug(slug: string): RegionMapping | undefined {
  return REGIONS.find((r) => r.slug === slug);
}

export function getDistrictBySlug(
  regionSlug: string,
  districtSlug: string
): DistrictMapping | undefined {
  return DISTRICTS.find(
    (d) => d.regionSlug === regionSlug && d.slug === districtSlug
  );
}

export function getDistrictsByRegion(regionSlug: string): DistrictMapping[] {
  return DISTRICTS.filter((d) => d.regionSlug === regionSlug);
}
